// packages/ui/src/components/SessionCard.tsx
import { Card, Flex, Text, Code, Box, HoverCard, Badge } from "@radix-ui/themes";
import type { Session, CIStatus } from "../data/schema";

interface SessionCardProps {
  session: Session;
}

const toolIcons: Record<string, string> = {
  Edit: "✏️",
  Write: "📝",
  Bash: "▶️",
  Read: "📖",
  Grep: "🔍",
  MultiEdit: "✏️",
};

function getCardClass(session: Session): string {
  const classes = ["session-card"];
  if (session.status === "working") {
    classes.push("status-working");
  }
  if (session.status === "waiting" && session.hasPendingToolUse) {
    classes.push("status-needs-approval");
  }
  return classes.join(" ");
}

function formatTimeAgo(isoString: string): string {
  const now = Date.now();
  const then = new Date(isoString).getTime();
  const diff = now - then;

  const seconds = Math.floor(diff / 1000);
  const minutes = Math.floor(seconds / 60);
  const hours = Math.floor(minutes / 60);
  const days = Math.floor(hours / 24);

  if (days > 0) return `${days}d`;
  if (hours > 0) return `${hours}h`;
  if (minutes > 0) return `${minutes}m`;
  return `${seconds}s`;
}

function formatTarget(target: string): string {
  // Shorten file paths
  if (target.includes("/")) {
    const parts = target.split("/");
    return parts[parts.length - 1];
  }
  // Truncate long commands
  if (target.length > 30) {
    return target.slice(0, 27) + "…";
  }
  return target;
}

function getRoleColor(role: "user" | "assistant" | "tool"): string {
  switch (role) {
    case "user":
      return "var(--blue-11)";
    case "assistant":
      return "var(--gray-12)";
    case "tool":
      return "var(--violet-11)";
  }
}

function getRolePrefix(role: "user" | "assistant" | "tool"): string {
  switch (role) {
    case "user":
      return "You: ";
    case "assistant":
      return "";
    case "tool":
      return "";
  }
}

function getCIStatusIcon(status: CIStatus): string {
  switch (status) {
    case "success":
      return "✓";
    case "failure":
      return "✗";
    case "running":
    case "pending":
      return "◎";
    case "cancelled":
      return "⊘";
    default:
      return "?";
  }
}

function getCIStatusColor(status: CIStatus): "green" | "red" | "yellow" | "gray" {
  switch (status) {
    case "success":
      return "green";
    case "failure":
      return "red";
    case "running":
    case "pending":
      return "yellow";
    default:
      return "gray";
  }
}

const API_BASE = "http://127.0.0.1:4451";

async function focusOrOpenSession(cwd: string, sessionId: string, status: string): Promise<"focused" | "opened" | "failed"> {
  try {
    const res = await fetch(`${API_BASE}/focus-or-open`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ cwd, sessionId, status }),
    });
    const data = await res.json();
    return data.action;
  } catch {
    return "failed";
  }
}

async function handleSessionClick(session: Session): Promise<void> {
  // Smart focus or open:
  // - Idle sessions always open new tab
  // - Active sessions try to focus existing tab
  await focusOrOpenSession(session.cwd, session.sessionId, session.status);
}

export function SessionCard({ session }: SessionCardProps) {
  const showPendingTool = session.hasPendingToolUse && session.pendingTool;
  // Show path from ~ (e.g., ~/programs/project)
  const dirPath = session.cwd.replace(/^\/Users\/[^/]+/, "~");

  return (
    <HoverCard.Root openDelay={300}>
      <HoverCard.Trigger>
        <Card size="2" className={getCardClass(session)} style={{ cursor: "pointer" }} onClick={() => handleSessionClick(session)}>
          <Flex direction="column" gap="2">
            {/* Header: directory and time */}
            <Flex justify="between" align="center">
              <Text size="1" color="gray" style={{ fontFamily: "var(--code-font-family)" }}>
                {dirPath}
              </Text>
              <Text size="1" color="gray">
                {formatTimeAgo(session.lastActivityAt)}
              </Text>
            </Flex>

            {/* Main content: goal as primary text */}
            <Text size="2" weight="medium" highContrast mb="1">
              {session.goal || session.originalPrompt.slice(0, 50)}
            </Text>

            {/* Secondary: current activity (pending tool or summary) */}
            {showPendingTool ? (
              <Flex align="center" gap="2">
                <Text size="1" color="gray">
                  {toolIcons[session.pendingTool!.tool]}
                </Text>
                <Code size="1" color="orange" variant="soft">
                  {session.pendingTool!.tool}: {formatTarget(session.pendingTool!.target)}
                </Code>
              </Flex>
            ) : (
              <Text size="1" color="gray">
                {session.summary}
              </Text>
            )}

            {/* Footer: branch/PR info and message count */}
            <Flex align="center" justify="between" gap="2">
              <Flex align="center" gap="2">
                {session.pr ? (
                  <a
                    href={session.pr.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    style={{ textDecoration: "none" }}
                  >
                    <Badge color={getCIStatusColor(session.pr.ciStatus)} variant="soft" size="1">
                      {getCIStatusIcon(session.pr.ciStatus)} #{session.pr.number}
                    </Badge>
                  </a>
                ) : session.gitBranch ? (
                  <Code size="1" variant="soft" color="gray">
                    {session.gitBranch.length > 20
                      ? session.gitBranch.slice(0, 17) + "..."
                      : session.gitBranch}
                  </Code>
                ) : null}
              </Flex>
              <Text size="1" color="gray">
                {session.messageCount} msgs
              </Text>
            </Flex>
          </Flex>
        </Card>
      </HoverCard.Trigger>

      <HoverCard.Content size="3" style={{ minWidth: "600px", minHeight: "400px" }}>
        <Flex direction="column" gap="3" style={{ height: "100%" }}>
          {/* Header: goal */}
          <Text size="2" weight="bold" highContrast>
            {session.goal || session.originalPrompt.slice(0, 60)}
          </Text>

          {/* Recent output */}
          <Box
            p="3"
            flexGrow="1"
            style={{
              backgroundColor: "var(--gray-2)",
              borderRadius: "var(--radius-3)",
              overflow: "auto",
            }}
          >
            {session.recentOutput?.length > 0 ? (
              session.recentOutput.map((output, i) => (
                <Text
                  key={i}
                  as="p"
                  size="1"
                  mb="2"
                  style={{
                    color: getRoleColor(output.role),
                    whiteSpace: "pre-wrap",
                    margin: 0,
                    marginBottom: i < session.recentOutput.length - 1 ? "8px" : 0,
                  }}
                >
                  {getRolePrefix(output.role)}
                  {output.content}
                </Text>
              ))
            ) : (
              <Text size="1" color="gray">
                No recent output
              </Text>
            )}
            {session.status === "working" && (
              <Text color="grass" size="1">█</Text>
            )}
          </Box>

          {/* PR Info if available */}
          {session.pr && (
            <Box>
              <Flex align="center" gap="2" mb="2">
                <a
                  href={session.pr.url}
                  target="_blank"
                  rel="noopener noreferrer"
                  style={{ fontSize: "var(--font-size-1)", fontWeight: 500 }}
                >
                  PR #{session.pr.number}: {session.pr.title}
                </a>
              </Flex>
              {session.pr.ciChecks.length > 0 && (
                <Flex gap="2" wrap="wrap">
                  {session.pr.ciChecks.map((check) => (
                    <Badge
                      key={check.name}
                      color={getCIStatusColor(check.status)}
                      variant="soft"
                      size="1"
                    >
                      {getCIStatusIcon(check.status)} {check.name.slice(0, 20)}
                    </Badge>
                  ))}
                </Flex>
              )}
            </Box>
          )}

          {/* Footer */}
          <Flex justify="between">
            <Text size="1" color="gray">
              {session.cwd.replace(/^\/Users\/\w+\//, "~/")}
            </Text>
            <Text size="1" color="gray">
              {session.sessionId.slice(0, 8)}
            </Text>
          </Flex>
        </Flex>
      </HoverCard.Content>
    </HoverCard.Root>
  );
}

// packages/ui-svelte/src/lib/components/SessionCard.svelte
<script lang="ts">
	import type { Session } from '$lib/data/schema';
	import { focusOrOpenSession, getLastAgentMessage } from '$lib/utils/api';
	import {
		formatTimeAgo,
		formatTarget,
		formatDirPath,
		getCIStatusIcon,
		getCIStatusColor,
		getRoleColor,
		getRolePrefix,
		toolIcons
	} from '$lib/utils/formatters';

	export let session: Session;

	$: showPendingTool = session.hasPendingToolUse && session.pendingTool;
	$: dirPath = formatDirPath(session.cwd);
	$: cardClasses = getCardClasses(session);

	function getCardClasses(session: Session): string {
		const classes = ['session-card', 'animate-slide-up'];
		if (session.status === 'working') {
			classes.push('animate-pulse-glow');
		}
		if (session.status === 'waiting' && session.hasPendingToolUse) {
			classes.push('animate-wiggle', 'status-needs-approval');
		}
		return classes.join(' ');
	}

	async function handleClick() {
		const lastAgentMessage = getLastAgentMessage(session);
		await focusOrOpenSession(session.cwd, session.sessionId, session.status, lastAgentMessage);
	}

	function handleKeydown(event: KeyboardEvent) {
		if (event.key === 'Enter' || event.key === ' ') {
			handleClick();
		}
	}

	let showHover = false;
</script>

<!-- svelte-ignore a11y_no_static_element_interactions -->
<div
	class="{cardClasses} relative bg-slate-2 border border-slate-6 rounded-lg p-3 cursor-pointer
		transition-all duration-200 ease-out overflow-hidden
		hover:-translate-y-1 hover:rotate-[0.5deg] hover:shadow-xl hover:shadow-slate-1/50"
	on:click={handleClick}
	on:keydown={handleKeydown}
	on:mouseenter={() => (showHover = true)}
	on:mouseleave={() => (showHover = false)}
	role="button"
	tabindex="0"
>
	<div class="flex flex-col gap-2 overflow-hidden">
		<!-- Header: directory and time -->
		<div class="flex justify-between items-center gap-2">
			<span class="text-xs text-slate-11 font-mono truncate">{dirPath}</span>
			<span class="text-xs text-slate-11 shrink-0">{formatTimeAgo(session.lastActivityAt)}</span>
		</div>

		<!-- Main content: goal -->
		<p class="text-sm font-medium text-slate-12 truncate">
			{session.goal || session.originalPrompt.slice(0, 50) || 'No goal'}
		</p>

		<!-- Secondary: pending tool or summary -->
		{#if showPendingTool && session.pendingTool}
			<div class="flex items-center gap-2 overflow-hidden">
				<span class="text-xs text-slate-11 shrink-0">{toolIcons[session.pendingTool.tool] || '🔧'}</span>
				<code class="text-xs bg-orange-3 text-orange-11 px-1.5 py-0.5 rounded truncate">
					{session.pendingTool.tool}: {formatTarget(session.pendingTool.target)}
				</code>
			</div>
		{:else}
			<p class="text-xs text-slate-11 truncate">{session.summary || 'No activity'}</p>
		{/if}

		<!-- Footer: branch/PR and message count -->
		<div class="flex items-center justify-between gap-2">
			<div class="flex items-center gap-2 overflow-hidden min-w-0">
				{#if session.pr}
					<a
						href={session.pr.url}
						target="_blank"
						rel="noopener noreferrer"
						on:click|stopPropagation
						class="inline-flex items-center gap-1 text-xs px-1.5 py-0.5 rounded
							bg-{getCIStatusColor(session.pr.ciStatus)}-3
							text-{getCIStatusColor(session.pr.ciStatus)}-11
							hover:opacity-80 shrink-0"
					>
						{getCIStatusIcon(session.pr.ciStatus)} #{session.pr.number}
					</a>
				{:else if session.gitBranch}
					<code class="text-xs bg-slate-3 text-slate-11 px-1.5 py-0.5 rounded truncate">
						{session.gitBranch.length > 20
							? session.gitBranch.slice(0, 17) + '...'
							: session.gitBranch}
					</code>
				{/if}
			</div>
			<span class="text-xs text-slate-11 shrink-0">{session.messageCount} msgs</span>
		</div>
	</div>

	<!-- Hover Card -->
	{#if showHover}
		<div
			class="absolute left-full top-0 ml-4 z-50 w-[500px] min-h-[300px] max-h-[400px]
				bg-slate-2 border border-slate-6 rounded-xl p-4 shadow-2xl
				flex flex-col gap-3"
		>
			<!-- Header: goal -->
			<h3 class="text-sm font-bold text-slate-12">
				{session.goal || session.originalPrompt.slice(0, 60)}
			</h3>

			<!-- Recent output -->
			<div class="flex-1 bg-slate-3 rounded-lg p-3 overflow-auto">
				{#if session.recentOutput?.length > 0}
					{#each session.recentOutput as output, i}
						<p
							class="{getRoleColor(output.role)} text-xs whitespace-pre-wrap"
							class:mb-2={i < session.recentOutput.length - 1}
						>
							{getRolePrefix(output.role)}{output.content}
						</p>
					{/each}
					{#if session.status === 'working'}
						<span class="text-grass-9 text-xs">█</span>
					{/if}
				{:else}
					<p class="text-xs text-slate-11">No recent output</p>
				{/if}
			</div>

			<!-- PR Info if available -->
			{#if session.pr}
				<div>
					<a
						href={session.pr.url}
						target="_blank"
						rel="noopener noreferrer"
						class="text-xs font-medium text-violet-11 hover:text-violet-12"
					>
						PR #{session.pr.number}: {session.pr.title}
					</a>
					{#if session.pr.ciChecks.length > 0}
						<div class="flex gap-2 flex-wrap mt-2">
							{#each session.pr.ciChecks as check}
								<span
									class="text-xs px-1.5 py-0.5 rounded
										bg-{getCIStatusColor(check.status)}-3
										text-{getCIStatusColor(check.status)}-11"
								>
									{getCIStatusIcon(check.status)}
									{check.name.slice(0, 20)}
								</span>
							{/each}
						</div>
					{/if}
				</div>
			{/if}

			<!-- Footer -->
			<div class="flex justify-between text-xs text-slate-11">
				<span class="font-mono">{dirPath}</span>
				<span class="font-mono">{session.sessionId.slice(0, 8)}</span>
			</div>
		</div>
	{/if}
</div>
